[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "microsoft-agents-hosting-msteams"
dynamic = ["version", "dependencies"]
description = "Integration library for Microsoft Agents with Teams"
readme = {file = "readme.md", content-type = "text/markdown"}
authors = [{name = "Microsoft Corporation"}]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]

[tool.setuptools.package-data]
"microsoft_agents.hosting.msteams" = ["py.typed"]

[tool.setuptools.packages.find]
include = ["microsoft_agents*"]

[project.urls]
"Homepage" = "https://github.com/microsoft/Agents"
